/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#001629',
          container: '#002b49',
          'on-primary': '#ffffff',
          'on-container': '#7293b6',
          inverse: '#a8caef',
          fixed: '#cfe5ff',
          'fixed-dim': '#a8caef',
          'on-fixed': '#001d34',
          'on-fixed-variant': '#274969',
        },
        secondary: {
          DEFAULT: '#a33d23',
          'on-secondary': '#ffffff',
          container: '#ff8162',
          'on-container': '#731a04',
          fixed: '#ffdad2',
          'fixed-dim': '#ffb4a2',
          'on-fixed': '#3c0700',
          'on-fixed-variant': '#83260e',
        },
        accent: '#E76F51',
        success: {
          DEFAULT: '#2A9D8F',
          'on-success': '#ffffff',
        },
        surface: {
          DEFAULT: '#fcf9f2',
          dim: '#dcdad3',
          bright: '#fcf9f2',
          'container-lowest': '#ffffff',
          'container-low': '#f6f3ec',
          container: '#f1eee7',
          'container-high': '#ebe8e1',
          'container-highest': '#e5e2db',
          variant: '#e5e2db',
          tint: '#406182',
        },
        'on-surface': '#1c1c18',
        'on-surface-variant': '#42474d',
        'inverse-surface': '#31312c',
        'inverse-on-surface': '#f3f0e9',
        outline: {
          DEFAULT: '#73777e',
          variant: '#c3c7ce',
          input: '#D1CDC2',
          card: '#EBE7DE',
        },
        background: '#fcf9f2',
        'on-background': '#1c1c18',
        error: {
          DEFAULT: '#ba1a1a',
          'on-error': '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        tertiary: {
          DEFAULT: '#001815',
          container: '#002f2a',
          'on-container': '#2fa092',
          fixed: '#8cf5e4',
          'fixed-dim': '#6fd8c8',
          'on-fixed': '#00201c',
          'on-fixed-variant': '#005048',
        },
      },
      fontFamily: {
        headline: ['Montserrat', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        coastal: '0 4px 12px rgba(0, 0, 0, 0.05)',
        'coastal-hover': '0 8px 24px rgba(0, 0, 0, 0.08)',
      },
      maxWidth: {
        container: '1280px',
      },
      spacing: {
        gutter: '24px',
        section: '48px',
      },
    },
  },
  plugins: [],
};
